# Support for codecov.

sudo: false
language: cpp
script:
  - export CC="gcc-4.8" CXX="g++-4.8"
  - mkdir -p Build+Debug
  - cd Build+Debug
  - cmake -DLIBOFP_ENABLE_CODE_COVERAGE=true -DLIBOFP_ENABLE_MEMCHECK_TESTS=false ..
  - ctest -D Experimental

os:
  - linux

addons:
  apt:
    sources:
      - kalakris-cmake
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - gcc-4.8
      - g++-4.8

before_install:
  - pip install codecov
after_success:
  - codecov
