language: cpp
compiler: clang
before_install:
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake
script: 
  - mkdir Build && cd Build
  - cmake .. && make test
